name: Sort Youtube Playlist

on:
  [workflow_dispatch]

jobs:
  sort:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Client Secret File
      run: |
        echo '${{ secrets.CLIENT_SECRETS_JSON }}' > client_secrets.json
        cat client_secrets.json
    - name: Sort PLaylist "En pause"
      run: dotnet run --project SortingYouTubePlaylist -- sort -p ${{ secrets.PLAYLIST_EN_PAUSE }}
