name: Sort Youtube Playlist

on:
  [workflow_dispatch]

jobs:
  sort:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Client Secret File
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "src/client_secrets.json"
        json: ${{ secrets.CLIENT_SECRETS_JSON }}
    - name: Create Token Reponse Directory
      run: mkdir youtube-data-store
    - name: Token Response File
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "src/youtube-data-store/Google.Apis.Auth.OAuth2.Responses.TokenResponse-user"
        json: ${{ secrets.TOKEN_RESPONSE_JSON }}
    - name: Sort PLaylist "En pause"
      run: dotnet run --project SortingYouTubePlaylist -- sort -p ${{ secrets.PLAYLIST_EN_PAUSE }}
    - name: Sort PLaylist "En cours"
      run: dotnet run --project SortingYouTubePlaylist -- sort -p ${{ secrets.PLAYLIST_EN_COURS }}
